; PlatformIO Project Configuration File

[env:ROS]
platform = raspberrypi
board = pico
framework = arduino
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
build_flags =
    -D ROS

board_microros_distro = humble
board_microros_transport = serial
