name: Motor Microcontroller CI

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "firmware/motor_microcontroller/**"
      - "firmware/shared/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "firmware/motor_microcontroller/**"
      - "firmware/shared/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.platformio/.cache
            ~/.platformio/packages
            ~/.platformio/platforms
            firmware/motor_microcontroller/.pio/libdeps
            firmware/motor_microcontroller/.pio/build
          key: ${{ runner.os }}-pio-motor-${{ hashFiles('firmware/motor_microcontroller/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-motor-
            ${{ runner.os }}-pio-
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install PlatformIO Core
        run: pip install platformio
      - name: Copy custom ROS interfaces
        run: |
          mkdir -p firmware/motor_microcontroller/extra_packages
          cp -r src/autogiro_interfaces firmware/motor_microcontroller/extra_packages/
      - name: Build PlatformIO Project
        run: pio run -e ROS
        working-directory: firmware/motor_microcontroller
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: motor_firmware.uf2
          path: firmware/motor_microcontroller/.pio/build/ROS/firmware.uf2
          if-no-files-found: warn
